---
title: "R Notebook"
output: html_notebook
---

```{r}

packages = c('magrittr','tidyverse','Rcpp','RcppArmadillo')

package.check <- lapply(packages, FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
        install.packages(x, dependencies = TRUE)
        library(x, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)
    }
})


```

```{r}

cppFunction('double ES_h(double p1, double p2) {
  double temp_var = 2 * asin(sqrt(p1)) - 2 * asin(sqrt(p2));
  return temp_var;
}')

ES_h_cpp()

ES_h_cpp(0.56, 0.42)

pwr::ES.h(0.56,0.42)
```

```{r}
pwr_package <- rbenchmark::benchmark(pwr::ES.h(0.5,0.2), replications = c(1000,5000,10000,50000,100000,500000,1000000)) %>% mutate(package = "pwr")

ES_h <- rbenchmark::benchmark(ES_h(0.5,0.2), replications = c(1000,5000,10000,50000,100000,500000,1000000)) %>% mutate(package = "cppwr")

dc1 <- rbind(pwr_package,ES_h)
```

```{r}

ggplot(dc1, aes(x = replications, y = elapsed, color = package)) +
       ggtitle("ES_h") +
       geom_point() +
       geom_line() + 
       scale_y_continuous("Elapsed Time") +
       scale_x_continuous("Replications") + 
       ggpubr::theme_classic2()

```

```{r}
library(Rcpp)

cppFunction('double ES_w1(double p0, double p1) {
  double temp_var = pow((p1-p0),2.0)/p0;
  return temp_var;
}')


ES_w1(0.5,0.2)
pwr::ES.w1(0.5,0.2)
ES_w2(0.5,0.2)
```


```{r}
pwr_package <- rbenchmark::benchmark(pwr::ES.w1(0.5,0.2), replications = c(1000,5000,10000)) %>% mutate(package = "pwr")

ES_w1 <- rbenchmark::benchmark(ES_w1(0.5,0.2), replications = c(1000,5000,10000)) %>% mutate(package = "cppwr")

dc2 <- rbind(pwr_package,ES_w1)
```

```{r}

ggplot(dc2, aes(x = replications, y = elapsed, color = package)) +
       ggtitle("ES_w1") +
       geom_point() +
       geom_line() + 
       scale_y_continuous("Elapsed Time") +
       scale_x_continuous("Replications") + 
       ggpubr::theme_classic2()

```


```{r}
m <- matrix(1:4, 2)

m
mn <- prop.table(m, 1)


"ES.w2" <-
function(P){
pi<-apply(P,1,sum) # sum rows of 2x2
pj<-apply(P,2,sum) # sum columns of 2x2
P0<-pi%*%t(pj) # matrix multiplication
sqrt(sum((P-P0)^2/P0))
}

ES.w2(m)

pi_t <- t(pi)
pi

pj


pi <- apply(m,1,sum)
pj <- apply(m,2,sum)

P0<-pi%*%t(pj)

P_test <- pi %*% t(pj)

?apply

pwr::ES.w2(mn)
```


```{r}
library(Rcpp)

cppFunction('double ES_w2(double p0, double p1) {
  double temp_var = pow((p1-p0),2.0)/p0;
  return temp_var;
}')

```













